# Generated by Django 4.2.3 on 2023-07-10 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("view_list_on_loan", "Get all book on loan"),),
            },
        ),
    ]
