# Generated by Django 4.2.3 on 2023-07-11 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (
                    ("view_list_on_loan", "Get all book on loan"),
                    ("can_mark_returned", "Can mark returned book"),
                ),
            },
        ),
    ]
