# Generated by Django 4.2.3 on 2023-07-11 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_bookinstance_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
